from fpdf import FPDF
import datetime
import os

class SkinAnalysisReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Skin Analysis Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(user_email, analysis_result, image_path, output_path):
    pdf = SkinAnalysisReport()
    pdf.add_page()
    
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f'Patient Email: {user_email}', 0, 1)
    pdf.cell(0, 10, f'Date: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1)
    pdf.ln(5)

    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 10, 'Analysis Summary', 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 10, f"Result: {analysis_result}")
    pdf.ln(10)

    if image_path and os.path.exists(image_path):
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, 'Analyzed Image:', 0, 1)
        try:
            pdf.image(image_path, x=10, w=100)
        except Exception as e:
            pdf.cell(0, 10, f'(Image could not be loaded)', 0, 1)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by an automated system and should be reviewed by a qualified medical professional.")

    pdf.output(output_path)
    return output_path
