import os
import datetime
from fpdf import FPDF

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Skinalyse Analysis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by Keshav - Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(user_name, result_text, confidence, report_path):
    """
    Matches the call in app_main.py: 
    export.generate_pdf_report(session['user'], session['last_result'], ...)
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Content
    pdf.cell(200, 10, txt=f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(200, 10, txt=f"Patient: {user_name}", ln=True)
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Diagnosis Summary:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Detected: {result_text}", ln=True)
    pdf.cell(200, 10, txt=f"Confidence: {confidence}", ln=True)

    # Ensure directory exists before saving
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    pdf.output(report_path)
    return report_path